sudo: required
services:
    - docker

before_install:
    - docker build -t pkn2009/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true pkn2009/react-test npm run test

after_success:
    - docker build -t pkn2009/multi-client ./client
    - docker build -t pkn2009/multi-nginx ./nginx
    - docker build -t pkn2009/multi-server ./server
    - docker build -t pkn2009/multi-worker ./worker
    # Login to Docker CLI
    # Push the images to Docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push pkn2009/multi-client
    - docker push pkn2009/multi-nginx
    - docker push pkn2009/multi-server
    - docker push pkn2009/multi-worker
    
